### ISSUE TITLE
Does this Still Work?

### ISSUE THREAD

**Issue by BigPrimeNumbers** [Graham--M/cotton-reboot-proton-fix#1]
Hey there! I appreciate you making the stub for this game. I've tried a few times to get this to work, and it doesn't seem to launch for me even after following all of the instructions. Does this still work for you using proton 9.0.2 and VS2019 via protontricks? Does the order of doing these steps matter? Does it have to be done on a fresh install of the game without having run it yet?

Incidentally, when I install VS2019, protontricks asks me 2-3 times to install the runtime, even after I accept and install it each time I'm asked. Did this happen for you?

**Comment by Graham--M** [comment]
Sorry for the late reply. The notification got flagged as spam in my email for some reason.

I did a fresh install using proton `9.0.3` and used `vcrun2019` and it still worked. The runtime installs a version for both 64-bit and 32-bit which is why you are getting asked multiple times.

I think the runtime isn't installing correctly for you. If you put `PROTON_LOG=1 %command%` into the steam launch options for the game, it should generate a file in your home directory called `steam-1656820.log` when you try run the game.

If you could attach the generated log file here then I'll take a look.

**Comment by BigPrimeNumbers** [comment]
I took a look at the log, and realized I had renamed the original DLL file incorrectly. Once I fixed that, it worked! Thanks again for your work on this :)

**Comment by Graham--M** [comment]
That's great! Remember to remove the modified launch options if you haven't done it already.
